2020-03-26 00:50:19,811 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 00:50:31,323 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 15:25:55,725 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 16:27:36,281 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 16:38:47,948 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 16:48:46,812 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 17:50:37,381 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 18:11:13,767 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 19:02:23,409 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:45]
2020-03-26 19:48:37,218 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:47]
2020-03-26 20:07:40,033 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:47]
2020-03-26 20:23:34,130 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:47]
2020-03-26 20:25:44,221 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:47]
2020-03-26 20:57:14,849 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:47]
2020-03-26 23:29:40,602 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:49]
2020-03-26 23:29:45,213 ERROR: Exception on /login [GET] [in c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Daniel\microblog\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Daniel\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Daniel\microblog\app\templates\base.html", line 47, in template
    {% block app_content %}{% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'app_content' defined twice
2020-03-26 23:33:16,882 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:49]
2020-03-27 00:33:26,329 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:51]
2020-03-27 00:45:14,763 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:51]
2020-03-27 00:53:10,527 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:51]
2020-03-27 00:57:01,703 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:51]
2020-03-27 00:57:44,145 INFO: Microblog startup [in C:\Users\Daniel\microblog\app\__init__.py:51]
2020-03-27 00:57:46,539 ERROR: Exception on / [GET] [in c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Daniel\microblog\app\routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Daniel\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Daniel\microblog\app\templates\base.html", line 1, in top-level template code
    {% block scripts %}
  File "C:\Users\Daniel\microblog\app\templates\base.html", line 2, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2020-03-27 00:57:48,921 ERROR: Exception on / [GET] [in c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Daniel\microblog\app\routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\daniel\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\daniel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Daniel\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Daniel\microblog\app\templates\base.html", line 1, in top-level template code
    {% block scripts %}
  File "C:\Users\Daniel\microblog\app\templates\base.html", line 2, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
